/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagegui;

/**
 *
 * @author brend
 */
public class InterfaceGraficaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraficaUsuario
     */
    public InterfaceGraficaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo1 = new javax.swing.JLabel();
        labelTexto2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        caixaDeTextoPrincipal = new javax.swing.JTextArea();
        labelBpm = new javax.swing.JLabel();
        caixaTextoBpm = new javax.swing.JTextField();
        labelInstrumento = new javax.swing.JLabel();
        boxOpcoesInstrumento = new javax.swing.JComboBox<>();
        botaoConverter = new javax.swing.JButton();
        botaoReproduzir = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(102, 0, 102));
        labelTitulo1.setText("Conversor de texto em música ");

        labelTexto2.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 19)); // NOI18N
        labelTexto2.setText("Insira na caixa de texto abaixo o texto que deseja converter em música ");

        caixaDeTextoPrincipal.setColumns(20);
        caixaDeTextoPrincipal.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        caixaDeTextoPrincipal.setRows(5);
        jScrollPane1.setViewportView(caixaDeTextoPrincipal);

        labelBpm.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelBpm.setText("Insira o BPM inicial ");

        caixaTextoBpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTextoBpmActionPerformed(evt);
            }
        });

        labelInstrumento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelInstrumento.setText("Escolha o instrumento inicial ");

        boxOpcoesInstrumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxOpcoesInstrumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Violão", "Bateria", "Guitarra", "Violino" }));

        botaoConverter.setBackground(new java.awt.Color(204, 204, 255));
        botaoConverter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoConverter.setText("Clique aqui para converter ");
        botaoConverter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 153, 255), null, null));

        botaoReproduzir.setBackground(new java.awt.Color(255, 204, 255));
        botaoReproduzir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoReproduzir.setText("Clique aqui para ouvir a música gerada");
        botaoReproduzir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jProgressBar1.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(labelTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelBpm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixaTextoBpm, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInstrumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botaoConverter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxOpcoesInstrumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(botaoReproduzir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaTextoBpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBpm))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInstrumento)
                    .addComponent(boxOpcoesInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoConverter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoReproduzir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaTextoBpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTextoBpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTextoBpmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraficaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraficaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraficaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraficaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraficaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConverter;
    private javax.swing.JButton botaoReproduzir;
    private javax.swing.JComboBox<String> boxOpcoesInstrumento;
    private javax.swing.JTextArea caixaDeTextoPrincipal;
    private javax.swing.JTextField caixaTextoBpm;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBpm;
    private javax.swing.JLabel labelInstrumento;
    private javax.swing.JLabel labelTexto2;
    private javax.swing.JLabel labelTitulo1;
    // End of variables declaration//GEN-END:variables
}
